// <auto-generated /> - This file is not auto generated but this is to prevent code formatting rules

using System;
using HarmonyLib;
using JetBrains.Annotations;

namespace ZeepSDK.Leaderboard.Patches;

[HarmonyPatch(typeof(OnlineTabLeaderboardUI), nameof(OnlineTabLeaderboardUI.Update))]
internal class OnlineTabLeaderboardUI_Update
{
    public static event Action<OnlineTabLeaderboardUI> Update;

    [UsedImplicitly]
    private static bool Prefix(OnlineTabLeaderboardUI __instance)
    {
        Update?.Invoke(__instance);
        return false;
    }
}
