name: Publish Plugin

on:
  workflow_dispatch:

jobs:
  install-unity:
    runs-on: windows-latest

    steps:
      - name: Download Unity Installer
        run: |
          Invoke-WebRequest -Uri "https://download.unity3d.com/download_unity/1c7d0df0160b/Windows64EditorInstaller/UnitySetup64-2021.3.10f1.exe" -OutFile "UnitySetup64.exe"

      - name: Run Silent Installation
        run: |
          Start-Process -FilePath ".\UnitySetup64.exe" -ArgumentList "/S", "/D=C:\Unity" -NoNewWindow -Wait
