name: Publish NuGet Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build, Test, and Pack
      run: dotnet build --configuration Release && dotnet test --configuration Release --no-build && dotnet pack --configuration Release --no-build --output ./nuget

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: donderjoekel

    - name: Publish NuGet package
      run: dotnet nuget push ./nuget/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}}
